/**
 * Traveller Core Rulebook - Power Plants
 *
 * Step 3 of spacecraft construction: power plant selection and sizing.
 *
 * Power requirements:
 *   Basic Ship Systems = 20% of hull tonnage
 *   Manoeuvre Drive    = 10% of hull tonnage × Thrust rating
 *   Jump Drive         = 10% of hull tonnage × Jump rating
 *
 * Fuel for power plant: 10% of PP tonnage per 4 weeks (min 1 ton)
 */

import type { PowerPlantType } from './types';

// ═══════════════════════════════════════════════════════════════════════
//  POWER PLANT TYPES
// ═══════════════════════════════════════════════════════════════════════

export const POWER_PLANT_TYPES: PowerPlantType[] = [
  {
    id: 'fusion_tl8',
    name: 'Fusion (TL8)',
    tl: 8,
    powerPerTon: 10,
    costPerTon: 0.5,
  },
  {
    id: 'fusion_tl12',
    name: 'Fusion (TL12)',
    tl: 12,
    powerPerTon: 15,
    costPerTon: 1,
  },
  {
    id: 'fusion_tl15',
    name: 'Fusion (TL15)',
    tl: 15,
    powerPerTon: 20,
    costPerTon: 2,
  },
];

// ═══════════════════════════════════════════════════════════════════════
//  POWER REQUIREMENT CALCULATIONS
// ═══════════════════════════════════════════════════════════════════════

/** Power needed for basic ship systems (lighting, gravity, life support) */
export function powerForBasicSystems(hullTonnage: number): number {
  return Math.ceil(hullTonnage * 0.2);
}

/** Power needed for manoeuvre drive */
export function powerForManoeuvreDrive(
  hullTonnage: number,
  thrustRating: number
): number {
  if (thrustRating <= 0) return 0;
  return Math.ceil(hullTonnage * 0.1 * thrustRating);
}

/** Power needed for jump drive */
export function powerForJumpDrive(
  hullTonnage: number,
  jumpRating: number
): number {
  if (jumpRating <= 0) return 0;
  return Math.ceil(hullTonnage * 0.1 * jumpRating);
}

/** Calculate power generated by a power plant */
export function calculatePowerGenerated(
  powerPlant: PowerPlantType,
  tons: number
): number {
  return powerPlant.powerPerTon * tons;
}

/** Calculate power plant cost in Credits */
export function calculatePowerPlantCost(
  powerPlant: PowerPlantType,
  tons: number
): number {
  return tons * powerPlant.costPerTon * 1_000_000;
}

/**
 * Calculate minimum power plant tonnage to meet a power requirement.
 * Returns the smallest whole-ton PP that generates >= requiredPower.
 */
export function minimumPowerPlantTons(
  powerPlant: PowerPlantType,
  requiredPower: number
): number {
  return Math.ceil(requiredPower / powerPlant.powerPerTon);
}

// ═══════════════════════════════════════════════════════════════════════
//  FUEL CALCULATIONS (Step 4)
// ═══════════════════════════════════════════════════════════════════════

/**
 * Jump fuel: 10% of hull tonnage × jump rating
 */
export function jumpFuelTons(
  hullTonnage: number,
  jumpRating: number
): number {
  if (jumpRating <= 0) return 0;
  return Math.ceil(hullTonnage * 0.1 * jumpRating);
}

/**
 * Power plant fuel for 4 weeks: 10% of PP tonnage (min 1 ton)
 * Additional weeks multiply proportionally.
 */
export function powerPlantFuelTons(
  powerPlantTonnage: number,
  weeksOfFuel: number = 4
): number {
  const baseFuel = Math.max(1, Math.ceil(powerPlantTonnage * 0.1));
  const multiplier = weeksOfFuel / 4;
  return Math.ceil(baseFuel * multiplier);
}

/** Total fuel tonnage (jump + power plant) */
export function totalFuelTons(
  hullTonnage: number,
  jumpRating: number,
  powerPlantTonnage: number,
  weeksOfFuel: number = 4
): number {
  return (
    jumpFuelTons(hullTonnage, jumpRating) +
    powerPlantFuelTons(powerPlantTonnage, weeksOfFuel)
  );
}
